### PR TITLE
Improve logging/254

### PR DESCRIPTION
**Pull request by kuba--**
Work on this issue (https://github.com/src-d/borges/issues/254) required:
- switch to logrus
- add new parameters (logformat, logtimeformat)
- integrate logrus hook for file names and numbers
- analyze code where we're working with real HDFS and where just with any remote
- resolve conflicts after rebase

### CODE REVIEW

**Comment by mcuadros** [comment]
I rather block this PR, since as discussed with @smola we prefer to implement a package Logger something like `gopkg.in/src-d/go-logger.v1` in order to:

- Standardize the configuration of the logging
- Be easy to configure to replace logrus with other libraries and limit the exposure of our project to a logurss API.
- Standardize the document the usage of the login in the projects.

**Comment by kuba--** [comment]
too late ;)
I'm totally agree on std. logging.
But I think, this PR was really about improving logging and std. logging could go as a independent PR/task.

**Comment by kuba--** [comment]
Shall I reopen?

**Comment by kuba--** [comment]
I've created a new issue for this: https://github.com/src-d/borges/issues/262

**Comment by mcuadros** [comment]
It's ok, but far as I know, the PRs are merged by the maintainer of the project, and after the approval from the maintainer. https://github.com/src-d/guide/blob/master/engineering/git-flow.md

**Comment by kuba--** [comment]
Sorry about that.
I've just noticed different practices among projects (except `go-git` which follows more strict rules).
Anyway - I should wait, so my bad.
On the other hand, IMO it will be clearer to move to std. logging in independent PR/issue.

**Pull request merged**
