### PR TITLE
Update go-queue to 1.0.2

### PR DESCRIPTION
**Pull request by jfontan**
* Add logging to republish producer
* Better performance republishing jobs

Fixes #305

### CODE REVIEW

**Comment by erizocosmico** [comment]
Shouldn't we reflect that version change in Gopkg.toml?

**Comment by ajnavarro** [comment]
Actually, we have framework as a dependency, and we shouldn't anymore, isn't it?

**Comment by jfontan** [comment]
I've left `Gopkg.toml` unchanged so next time we want to upgrade we don't have to edit it. The version is already in the lock file and won't be changed until `-update` is used with the library.

Should we set all the versions in the toml file?

**Comment by erizocosmico** [comment]
If it's a minimum requirement for it to work I'd say yes. If it's just a "performance improvements" maybe a ">x.y.z" (don't remember if dep allows that) would be fine.

**Comment by jfontan** [comment]
Added the constraint `~1.0.2`, that is `>=1.0.2`, `<1.1.0`. We can upgrade to any patch release after this one.

Framework is still used to get database configuration:

https://github.com/src-d/borges/blob/master/cli/borges/init.go#L28

**Pull request merged**
