### PR TITLE
Makefile: ensure dependencies rule is overriden

### PR DESCRIPTION
**Pull request by smola**

### CODE REVIEW

**Comment by bzz** [comment]
Not sure what is the test plan for this, but changes look good to me.

**Comment by bzz** [comment]
This seems to be the fix for https://github.com/src-d/borges/pull/69#issuecomment-311950369 so lets :shipit: !

**Comment by bzz** [comment]
Ok, may be I'm doing something wrong here :/ - tested by applying this fix to #96 locally and still could not build `borges`

<details>

```
make packages                                                                        
Makefile:29: warning: overriding commands for target `dependencies'
Makefile.main:59: warning: ignoring old commands for target `dependencies'
Makefile:41: warning: overriding commands for target `test'
Makefile.main:149: warning: ignoring old commands for target `test'
Makefile:44: warning: overriding commands for target `test-coverage'
Makefile.main:152: warning: ignoring old commands for target `test-coverage'
consumer.go:6:2: cannot find package "gopkg.in/src-d/core-retrieval.v0" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/core-retrieval.v0 (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/core-retrieval.v0 (from $GOPATH)
../../mentionjobiter.go:4:2: cannot find package "gopkg.in/src-d/core-retrieval.v0/model" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/core-retrieval.v0/model (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/core-retrieval.v0/model (from $GOPATH)
../../archiver.go:11:2: cannot find package "gopkg.in/src-d/core-retrieval.v0/repository" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/core-retrieval.v0/repository (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/core-retrieval.v0/repository (from $GOPATH)
../../common.go:10:2: cannot find package "gopkg.in/src-d/core.v0" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/core.v0 (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/core.v0 (from $GOPATH)
../../archiver.go:12:2: cannot find package "gopkg.in/src-d/core.v0/model" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/core.v0/model (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/core.v0/model (from $GOPATH)
../../consumer.go:7:2: cannot find package "gopkg.in/src-d/framework.v0/queue" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/framework.v0/queue (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/framework.v0/queue (from $GOPATH)
../../archiver.go:15:2: cannot find package "gopkg.in/src-d/go-errors.v0" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/go-errors.v0 (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/go-errors.v0 (from $GOPATH)
borges_darwin_amd64/
consumer.go:6:2: cannot find package "gopkg.in/src-d/core-retrieval.v0" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/core-retrieval.v0 (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/core-retrieval.v0 (from $GOPATH)
../../mentionjobiter.go:4:2: cannot find package "gopkg.in/src-d/core-retrieval.v0/model" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/core-retrieval.v0/model (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/core-retrieval.v0/model (from $GOPATH)
../../archiver.go:11:2: cannot find package "gopkg.in/src-d/core-retrieval.v0/repository" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/core-retrieval.v0/repository (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/core-retrieval.v0/repository (from $GOPATH)
../../common.go:10:2: cannot find package "gopkg.in/src-d/core.v0" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/core.v0 (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/core.v0 (from $GOPATH)
../../archiver.go:12:2: cannot find package "gopkg.in/src-d/core.v0/model" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/core.v0/model (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/core.v0/model (from $GOPATH)
../../consumer.go:7:2: cannot find package "gopkg.in/src-d/framework.v0/queue" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/framework.v0/queue (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/framework.v0/queue (from $GOPATH)
../../archiver.go:15:2: cannot find package "gopkg.in/src-d/go-errors.v0" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/src-d/go-errors.v0 (from $GOROOT)
	/Users/alex/go/src/gopkg.in/src-d/go-errors.v0 (from $GOPATH)
borges_linux_amd64/
```
</details>

**Comment by smola** [comment]
@bzz macOS? `make -version`?

**Comment by bzz** [comment]
Followup up with discussion \w @smola that happened elsewhere

```
Santiago [2:59 PM] 
@alex it's not working, can you `rm -rf vendor` and try again?


Alex [3:00 PM] 
ls -la vendor
ls: cannot access 'vendor': No such file or directory


Santiago [3:01 PM] 
hah
let me check
```

**Comment by smola** [comment]
Merging, since there is no regression. Anyway, we're migrating to `src-d/ci`-based solution.

**Pull request merged**
