### PR TITLE
k8s: update deployments

### PR DESCRIPTION
**Pull request by erizocosmico**

### CODE REVIEW

**Comment by jfontan** [comment]
While you're at it may be nice to add `CONFIG_ROOT_REPOSITORIES_TEMP_DIR`.

**Comment by erizocosmico** [comment]
Right! Which dir should I put? Something inside `/tmp`?

**Comment by jfontan** [comment]
I would put it in an HDFS directory specific to this deployment, maybe `/borges/tmp`.

**Comment by erizocosmico** [comment]
Done @jfontan

**Pull request merged**
