### PR TITLE
store IsFork option to rooted repo config

### PR DESCRIPTION
**Pull request by smola**
`isfork` is set to `true` or `false` in each remote git config section.

The resulting remote would look as follows:
```
[remote "015da250-023c-7e4a-f9ec-c27767c3bf6d"]
url = git://some/repo.git
url = https://some/repo.git
isfork = true
```

### CODE REVIEW

**Comment by bzz** [comment]
If possible, could you please also add a text description of the config format to the PR?

**Comment by smola** [comment]
@bzz :+1: Updated. To read more about git config, see https://git-scm.com/docs/git-config
However, either go-git or jgit exposes API to work with it.

**Comment by bzz** [comment]
Thanks for the link!  Sorry if that is something obvious, but I can not find `remote git config section` in the text though.

I have read that before and that's why was wondering about details of

```
AFAIK it's KV with composite key and ability to set/unset key and value by regex

git config <section>.<sub-section>.<keyname> value
```

Could you please clarify key structure, or am I missing something here?

**Comment by smola** [comment]
@bzz 
* section: `remote`
* subsection: repository ULID (one subsection for each repository
* keyname: `isfork`

**Comment by bzz** [comment]
Got it! Thanks

From the test case, it looks like

```
remote.<ULID>.url : <url>
remote.<ULID>.isfork: <true|false>
```

As far as I understand, it should be possible to get all ULIDs with `isfork` in single API call \w regexp. Nice

**Pull request merged**
