### PR TITLE
upgrade dependencies

### PR DESCRIPTION
**Pull request by erizocosmico**

### CODE REVIEW

**Comment by ajnavarro** [comment]
I think we should upload only the go-git dependency, just to avoid collateral errors.

**Comment by jbeardly** [comment]
Why the files are not being uploaded?

**Comment by jbeardly** [comment]
And maybe is time to change to dep

**Comment by ajnavarro** [comment]
> And maybe is time to change to dep

This is not related with this PR, and can be made separately

**Comment by erizocosmico** [comment]
@jfontan was taking care of this in the core-retrieval side

**Pull request closed without merging**
